### ISSUE TITLE
tomcat error

### ISSUE THREAD

**Issue by jeongggggg** [jeongggggg/lotto-random-number#2]
12-Jul-2024 23:01:15.856 SEVERE [main] org.apache.catalina.core.StandardServer.await 주소 [localhost]와(과) 포트 [8005]에, 서버 셧다운 소켓을 생성하지 못했습니다. (base 포트 [8005], offset [0])
	java.net.BindException: Address already in use
		at java.base/sun.nio.ch.Net.bind0(Native Method)
		at java.base/sun.nio.ch.Net.bind(Net.java:565)
		at java.base/sun.nio.ch.Net.bind(Net.java:554)
		at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:636)
		at java.base/java.net.ServerSocket.bind(ServerSocket.java:390)
		at java.base/java.net.ServerSocket.<init>(ServerSocket.java:277)
		at org.apache.catalina.core.StandardServer.await(StandardServer.java:541)
		at org.apache.catalina.startup.Catalina.await(Catalina.java:825)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:773)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
12-Jul-2024 23:01:15.856 INFO [main] org.apache.coyote.AbstractProtocol.pause 프로토콜 핸들러 ["http-nio-8080"]을(를) 일시 정지 중
12-Jul-2024 23:01:15.856 INFO [main] org.apache.catalina.core.StandardService.stopInternal 서비스 [Catalina]을(를) 중지시킵니다.
12-Jul-2024 23:01:15.861 INFO [main] org.apache.coyote.AbstractProtocol.stop 프로토콜 핸들러 ["http-nio-8080"]을(를) 중지시킵니다.
12-Jul-2024 23:01:15.861 INFO [main] org.apache.coyote.AbstractProtocol.destroy 프로토콜 핸들러 ["http-nio-8080"]을(를) 소멸시킵니다.

**Comment by jeongggggg** [comment]
Tomcat 서버가 포트 8005에 바인딩할 수 없다는 오류 메시지 
이 문제는 다른 인스턴스의 Tomcat 서버나 다른 애플리케이션이 해당 포트를 사용 중일 때 발생할 수 있다.

1. 포트 8005를 사용 중인 프로세스를 확인
`lsof -i :8005`

2. 결과

`COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java    31322 ahjeong   53u  IPv6 0x984843e1d189c625      0t0  TCP localhost:8005 (LISTEN)`

3. PID(프로세스 ID)를 확인한 후, 해당 PID를 종료

`  kill -9 31322`

4. Tomcat 서버 재시작
`cd /path/to/tomcat/bin
./startup.sh`
